server:
  port: 8080

spring:
  application:
    name: learn-ed-gateway

eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
      register-with-eureka: true
      fetch-registry: true
    instance:
        preferIpAddress: true
        instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
        leaseRenewalIntervalInSeconds: 1
        leaseExpirationDurationInSeconds: 2
